table DIM_DEPUTADO
	lineageTag: e63709f2-1fdf-4601-8ffb-9e250c4efcd8

	column id
		dataType: int64
		formatString: 0
		lineageTag: d21b50a9-a922-401a-9784-4df3435d5ebf
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column nomeCivil
		dataType: string
		lineageTag: 3674437b-e603-4c43-bc4a-ad0ddb7af7fd
		summarizeBy: none
		sourceColumn: nomeCivil

		annotation SummarizationSetBy = Automatic

	column 'ultimoStatus.nome'
		dataType: string
		lineageTag: 8b2b698c-c2b9-4bd2-afa7-c9b37d48a9a8
		summarizeBy: none
		sourceColumn: ultimoStatus.nome

		annotation SummarizationSetBy = Automatic

	column 'ultimoStatus.idLegislatura'
		dataType: int64
		formatString: 0
		lineageTag: 19d74d02-7d6e-4131-88b3-d98671aefb4d
		summarizeBy: sum
		sourceColumn: ultimoStatus.idLegislatura

		annotation SummarizationSetBy = Automatic

	column 'ultimoStatus.urlFoto'
		dataType: string
		lineageTag: 1641bffc-bd30-4882-ac17-17cccdb5ea4b
		summarizeBy: none
		sourceColumn: ultimoStatus.urlFoto

		annotation SummarizationSetBy = Automatic

	column 'ultimoStatus.nomeEleitoral'
		dataType: string
		lineageTag: efad7e8f-0d51-49ee-b720-cb32db27d4b4
		summarizeBy: none
		sourceColumn: ultimoStatus.nomeEleitoral

		annotation SummarizationSetBy = Automatic

	column 'ultimoStatus.condicaoEleitoral'
		dataType: string
		lineageTag: 938749d1-f7b8-415d-8877-6ed750bf6b44
		summarizeBy: none
		sourceColumn: ultimoStatus.condicaoEleitoral

		annotation SummarizationSetBy = Automatic

	column cpf
		dataType: int64
		formatString: 0
		lineageTag: 4fe93db6-716d-4018-acf7-cb18620bb703
		summarizeBy: sum
		sourceColumn: cpf

		annotation SummarizationSetBy = Automatic

	column sexo
		dataType: string
		lineageTag: edbba857-8c1c-4076-afd4-6e47745e987d
		summarizeBy: none
		sourceColumn: sexo

		annotation SummarizationSetBy = Automatic

	column urlWebsite
		dataType: string
		lineageTag: eb7a6b48-db68-4969-9ff0-cd1b975995af
		summarizeBy: none
		sourceColumn: urlWebsite

		annotation SummarizationSetBy = Automatic

	column dataNascimento
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8fbb2efc-b066-47e0-8a62-be58a29a0f78
		summarizeBy: none
		sourceColumn: dataNascimento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dataFalecimento
		dataType: string
		lineageTag: 5b950bbc-ee6b-48b8-8011-79b36c6e3411
		summarizeBy: none
		sourceColumn: dataFalecimento

		annotation SummarizationSetBy = Automatic

	column escolaridade
		dataType: string
		lineageTag: 654d295e-850c-488c-9276-1bf5c6e128e1
		summarizeBy: none
		sourceColumn: escolaridade

		annotation SummarizationSetBy = Automatic

	column idPartido
		dataType: int64
		formatString: 0
		lineageTag: acdb4a07-3f89-457d-b127-5ab3644a7f5e
		summarizeBy: none
		sourceColumn: idPartido

		annotation SummarizationSetBy = Automatic

	column idUf
		dataType: int64
		formatString: 0
		lineageTag: 53104c9c-00fa-4fa5-bf93-5fc3ec10d335
		summarizeBy: none
		sourceColumn: idUf

		annotation SummarizationSetBy = Automatic

	partition DIM_DEPUTADO = m
		mode: import
		source =
				let
				    Fonte = Json.Document(File.Contents("C:\Users\MariaJuliaEscobarCor\Downloads\CPA\Untitled Folder 1\deputados_detalhados.json")),
				    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Column1 Expandido" = Table.ExpandRecordColumn(#"Convertido para Tabela", "Column1", {"id", "uri", "nomeCivil", "ultimoStatus", "cpf", "sexo", "urlWebsite", "redeSocial", "dataNascimento", "dataFalecimento", "ufNascimento", "municipioNascimento", "escolaridade"}, {"id", "uri", "nomeCivil", "ultimoStatus", "cpf", "sexo", "urlWebsite", "redeSocial", "dataNascimento", "dataFalecimento", "ufNascimento", "municipioNascimento", "escolaridade"}),
				    #"ultimoStatus Expandido" = Table.ExpandRecordColumn(#"Column1 Expandido", "ultimoStatus", {"id", "uri", "nome", "siglaPartido", "uriPartido", "siglaUf", "idLegislatura", "urlFoto", "email", "data", "nomeEleitoral", "gabinete", "situacao", "condicaoEleitoral", "descricaoStatus"}, {"ultimoStatus.id", "ultimoStatus.uri", "ultimoStatus.nome", "ultimoStatus.siglaPartido", "ultimoStatus.uriPartido", "ultimoStatus.siglaUf", "ultimoStatus.idLegislatura", "ultimoStatus.urlFoto", "ultimoStatus.email", "ultimoStatus.data", "ultimoStatus.nomeEleitoral", "ultimoStatus.gabinete", "ultimoStatus.situacao", "ultimoStatus.condicaoEleitoral", "ultimoStatus.descricaoStatus"}),
				    #"ultimoStatus.gabinete Expandido" = Table.ExpandRecordColumn(#"ultimoStatus Expandido", "ultimoStatus.gabinete", {"nome", "predio", "sala", "andar", "telefone", "email"}, {"ultimoStatus.gabinete.nome", "ultimoStatus.gabinete.predio", "ultimoStatus.gabinete.sala", "ultimoStatus.gabinete.andar", "ultimoStatus.gabinete.telefone", "ultimoStatus.gabinete.email"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"ultimoStatus.gabinete Expandido",{{"id", Int64.Type}, {"uri", type text}, {"nomeCivil", type text}, {"ultimoStatus.id", Int64.Type}, {"ultimoStatus.uri", type text}, {"ultimoStatus.nome", type text}, {"ultimoStatus.siglaPartido", type text}, {"ultimoStatus.uriPartido", type any}, {"ultimoStatus.siglaUf", type text}, {"ultimoStatus.idLegislatura", Int64.Type}, {"ultimoStatus.urlFoto", type text}, {"ultimoStatus.email", type any}, {"ultimoStatus.data", type date}, {"ultimoStatus.nomeEleitoral", type text}, {"ultimoStatus.gabinete.nome", Int64.Type}, {"ultimoStatus.gabinete.predio", type text}, {"ultimoStatus.gabinete.sala", Int64.Type}, {"ultimoStatus.gabinete.andar", Int64.Type}, {"ultimoStatus.gabinete.telefone", type text}, {"ultimoStatus.gabinete.email", type text}, {"ultimoStatus.situacao", type text}, {"ultimoStatus.condicaoEleitoral", type text}, {"ultimoStatus.descricaoStatus", type any}, {"cpf", Int64.Type}, {"sexo", type text}, {"urlWebsite", type text}, {"redeSocial", type any}, {"dataNascimento", type date}, {"dataFalecimento", type any}, {"ufNascimento", type text}, {"municipioNascimento", type text}, {"escolaridade", type text}}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Tipo Alterado", {"ultimoStatus.siglaPartido"}, DIM_PARTIDO, {"siglaPartido"}, "DIM_PARTIDO", JoinKind.LeftOuter),
				    #"DIM_PARTIDO Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "DIM_PARTIDO", {"idPartido"}, {"DIM_PARTIDO.idPartido"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"DIM_PARTIDO Expandido",{{"DIM_PARTIDO.idPartido", "idPartido"}}),
				    #"Consultas Mescladas1" = Table.NestedJoin(#"Colunas Renomeadas", {"ultimoStatus.siglaUf"}, DIM_ESTADO, {"siglaUf"}, "DIM_ESTADO", JoinKind.LeftOuter),
				    #"DIM_ESTADO Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "DIM_ESTADO", {"idUf"}, {"DIM_ESTADO.idUf"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"DIM_ESTADO Expandido",{{"DIM_ESTADO.idUf", "idUf"}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Renomeadas1",{"uri", "ultimoStatus.id", "ultimoStatus.uri", "ultimoStatus.siglaPartido", "ultimoStatus.uriPartido", "ultimoStatus.siglaUf", "ultimoStatus.email", "ultimoStatus.data", "ultimoStatus.gabinete.nome", "ultimoStatus.gabinete.predio", "ultimoStatus.gabinete.sala", "ultimoStatus.gabinete.andar", "ultimoStatus.gabinete.telefone", "ultimoStatus.gabinete.email", "ultimoStatus.situacao", "ultimoStatus.descricaoStatus", "redeSocial", "ufNascimento", "municipioNascimento"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

